language: php

addons:
  postgresql: "9.5"

services:
  - postgresql

php:
  - 5.6
  - 7.0

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - psql -c "CREATE USER flexibudget WITH PASSWORD 'flexibudget'" -U postgres
  - psql -c 'CREATE DATABASE flexibudget OWNER flexibudget;' -U postgres
  
script:
  - mkdir -p build
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phinx migrate
  - ./vendor/bin/phinx  seed:run -v  -s UserSeeder -s BudgetSeeder -s IntendSeeder
  - cd tests
  - ../vendor/bin/phpunit -c configuration.xml --bootstrap Bootstrap.php src
  - echo commented now ./vendor/bin/phpcs src --standard=psr2 -sp

after_script:
  - php vendor/bin/coveralls

