-- MySQL Script generated by MySQL Workbench
-- Po 24. říjen 2016, 20:22:22 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flexibudget` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `flexibudget` ;

-- -----------------------------------------------------
-- Table `flexibudget`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flexibudget`.`User` (
  `id` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `priviliges` VARCHAR(45) NULL,
  `created_at` DATE NULL,
  `last_login_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flexibudget`.`Budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flexibudget`.`Budget` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `approval_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flexibudget`.`BudgerRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flexibudget`.`BudgerRecord` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `limit` DECIMAL(10,0) NULL,
  `Budget_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BudgerRecord_Budget_idx` (`Budget_id` ASC),
  INDEX `fk_BudgerRecord_user1_idx` (`User_id` ASC),
  CONSTRAINT `fk_BudgerRecord_Budget`
    FOREIGN KEY (`Budget_id`)
    REFERENCES `flexibudget`.`Budget` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BudgerRecord_user1`
    FOREIGN KEY (`User_id`)
    REFERENCES `flexibudget`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flexibudget`.`Intend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flexibudget`.`Intend` (
  `id` INT NOT NULL,
  `limit` DECIMAL(10,0) NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `approval_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flexibudget`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flexibudget`.`Invoice` (
  `id` INT NOT NULL,
  `value` DECIMAL(10,0) NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `created_ad` DATE NULL,
  `approval_at` DATE NULL,
  `paid_at` DATE NULL,
  `User_id` INT NOT NULL,
  `BudgerRecord_id` INT NOT NULL,
  `Intend_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vydaj_user1_idx` (`User_id` ASC),
  INDEX `fk_Invoice_BudgerRecord1_idx` (`BudgerRecord_id` ASC),
  INDEX `fk_Invoice_Intend1_idx` (`Intend_id` ASC),
  CONSTRAINT `fk_vydaj_user1`
    FOREIGN KEY (`User_id`)
    REFERENCES `flexibudget`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_BudgerRecord1`
    FOREIGN KEY (`BudgerRecord_id`)
    REFERENCES `flexibudget`.`BudgerRecord` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Intend1`
    FOREIGN KEY (`Intend_id`)
    REFERENCES `flexibudget`.`Intend` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flexibudget`.`Voting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flexibudget`.`Voting` (
  `id` INT NOT NULL,
  `Intend_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hlasovani_zamer1_idx` (`Intend_id` ASC),
  INDEX `fk_hlasovani_user1_idx` (`User_id` ASC),
  CONSTRAINT `fk_hlasovani_zamer1`
    FOREIGN KEY (`Intend_id`)
    REFERENCES `flexibudget`.`Intend` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hlasovani_user1`
    FOREIGN KEY (`User_id`)
    REFERENCES `flexibudget`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
