#!/bin/bash
# postinst script for flexibudget

set -e
. /usr/share/debconf/confmodule


#Replace Key Value in Config File
function replace {
    cfg="/usr/share/flexibudget/includes/config.php"
    sed -i "/${1}'/c\define('${1}', '${2}');" $cfg
}

listOfConfigs="FLEXIBEE_URL
FLEXIBEE_LOGIN
FLEXIBEE_PASSWORD
FLEXIBEE_COMPANY
DATABASE_TYPE
DATABASE_HOST
DATABASE_PORT
DATABASE_USER
DATABASE_PASSWORD
DATABASE_NAME"

for keyword in "$listOfConfigs"
do
  db_get "flexibudget/$keyword"
  if [ "$RET" = "false" ]; then
    db_input critical "flexibudget/$keyword" || true
    db_go
    fi
 replace "$keyword" $RET
done

if [ -x /usr/sbin/a2enconf ] ; then
    a2enconf flexibudget
fi

if [ -f /etc/init.d/apache2 ] ; then
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d apache2 reload 3>/dev/null || true
    else
        /etc/init.d/apache2 reload 3>/dev/null || true
    fi
fi

if [ -f /etc/init.d/avahi ] ; then
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d avahi reload 3>/dev/null || true
    else
        /etc/init.d/avahi reload 3>/dev/null || true
    fi
fi

#DEBHELPER#

exit 0
